# Generated by Django 6.0.8 on 2026-08-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine_trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(db_index=True, max_length=120)),
                ('proposal_id', models.CharField(blank=True, max_length=120)),
                ('contract_type', models.CharField(max_length=40)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('duration_unit', models.CharField(default='m', max_length=12)),
                ('barrier', models.CharField(blank=True, max_length=40)),
                ('buy_price', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('payout', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('settlement', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('profit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('status', models.CharField(default='purchased', max_length=24)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='engine_trading.position')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract_id', 'status'], name='contracts_c_contrac_18b952_idx')],
            },
        ),
    ]
