# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('engine_trading', '0002_position_engine_trad_symbol_e12ea2_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_id', 'status'], name='contracts_c_contrac_18b952_idx'),
        ),
    ]
