# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_trading', '0001_initial'),
        ('execution', '0002_rename_execution_q_status_f45c9d_idx_execution_e_status_3031dd_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['symbol', 'status'], name='engine_trad_symbol_e12ea2_idx'),
        ),
    ]
