# Generated by Django 6.0.8 on 2026-08-26 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40)),
                ('strategy', models.CharField(blank=True, max_length=120)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=12)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'), ('trailing_stop', 'Trailing Stop')], default='market', max_length=32)),
                ('stake', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('queued', 'Queued'), ('sent_to_broker', 'Sent To Broker'), ('accepted', 'Accepted'), ('executed', 'Executed'), ('archived', 'Archived'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('broker_reference', models.CharField(blank=True, db_index=True, max_length=160)),
                ('client_request_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('validation_context', models.JSONField(blank=True, default=dict)),
                ('broker_payload', models.JSONField(blank=True, default=dict)),
                ('broker_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_orders', to='brokers.brokeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('queue_type', models.CharField(default='priority', max_length=24)),
                ('next_retry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='execution.order')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=32)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('broker_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='execution.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='execution_o_user_id_909c17_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_account', 'symbol'], name='execution_o_broker__9b74d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('user', 'client_request_id'), name='unique_execution_client_request'),
        ),
        migrations.AddIndex(
            model_name='executionqueue',
            index=models.Index(fields=['status', 'next_retry', 'priority'], name='execution_e_status_3031dd_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['order', '-created_at'], name='execution_e_order_i_994985_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['event', 'status'], name='execution_e_event_4b367d_idx'),
        ),
    ]
