# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='executionqueue',
            new_name='execution_e_status_3031dd_idx',
            old_name='execution_q_status_f45c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='execution_o_user_id_909c17_idx',
            old_name='execution_o_user_id_3ad51a_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('queued', 'Queued'), ('sent_to_broker', 'Sent To Broker'), ('accepted', 'Accepted'), ('executed', 'Executed'), ('archived', 'Archived'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['order', '-created_at'], name='execution_e_order_i_994985_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['event', 'status'], name='execution_e_event_4b367d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_account', 'symbol'], name='execution_o_broker__9b74d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('user', 'client_request_id'), name='unique_execution_client_request'),
        ),
    ]
