# Generated by Django 6.0.8 on 2026-08-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_reconciliationevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reconciliationevent',
            new_name='execution_r_broker__627b64_idx',
            old_name='execution_r_broker_a_5c5c9f_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationevent',
            new_name='execution_r_user_id_0046be_idx',
            old_name='execution_r_user_id_8fcb15_idx',
        ),
    ]
