"""Broker contracts used by trading code instead of vendor SDKs."""
from typing import Any, Protocol


class BrokerInterface(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def buy(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def sell(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def balance(self) -> dict[str, Any]: ...
    async def history(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def positions(self) -> dict[str, Any]: ...
    async def orders(self) -> dict[str, Any]: ...
    async def subscribe_ticks(self, symbol: str) -> str: ...
