# Generated by Django 6.0.6 on 2026-07-04 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_trade_id', models.CharField(help_text='Original leader trade identifier', max_length=64)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_trades', to=settings.AUTH_USER_MODEL)),
                ('follower_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_copied_trade', to='trading.trade')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.IntegerField(default=0)),
                ('assets_under_management', models.FloatField(default=0.0)),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('avg_return_pct', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assets_under_management'],
            },
        ),
        migrations.CreateModel(
            name='CopyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_type', models.CharField(choices=[('PERCENT', 'Percent of follower equity'), ('FIXED', 'Fixed amount')], default='PERCENT', max_length=10)),
                ('allocation_value', models.FloatField(default=10.0, help_text='Percent when PERCENT, amount in account currency when FIXED')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('leader', 'follower')},
            },
        ),
    ]
