# Generated manually because the execution environment does not include Django.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_copytrade_leaderstats_copyfollow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField("trade", "client_request_id", models.CharField(blank=True, db_index=True, max_length=80)),
        migrations.AddField("trade", "broker_reference", models.CharField(blank=True, db_index=True, max_length=160)),
        migrations.AlterField("trade", "status", models.CharField(choices=[("NEW", "New"), ("VALIDATED", "Validated"), ("QUEUED", "Queued"), ("SUBMITTED", "Submitted"), ("ACCEPTED", "Accepted"), ("OPEN", "Open"), ("PARTIALLY_CLOSED", "Partially Closed"), ("CLOSED", "Closed"), ("ARCHIVED", "Archived"), ("CANCELLED", "Cancelled")], default="OPEN", max_length=20)),
        migrations.CreateModel(name="TradeStateTransition", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("from_state", models.CharField(blank=True, max_length=20)), ("to_state", models.CharField(max_length=20)), ("reason", models.TextField(blank=True)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("trade", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="state_transitions", to="trading.trade"))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="TradeExecution", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("broker", models.CharField(default="deriv", max_length=60)), ("status", models.CharField(db_index=True, max_length=40)), ("request_payload", models.JSONField(blank=True, default=dict)), ("response_payload", models.JSONField(blank=True, default=dict)), ("latency_ms", models.FloatField(default=0)), ("attempt", models.PositiveSmallIntegerField(default=1)), ("created_at", models.DateTimeField(auto_now_add=True)), ("trade", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="executions", to="trading.trade"))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="PortfolioSnapshot", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("balance", models.FloatField(default=0)), ("equity", models.FloatField(default=0)), ("margin", models.FloatField(default=0)), ("open_positions", models.PositiveIntegerField(default=0)), ("daily_pnl", models.FloatField(default=0)), ("risk_utilization", models.FloatField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_snapshots", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="StrategyPerformance", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("symbol", models.CharField(blank=True, max_length=20)), ("total_trades", models.PositiveIntegerField(default=0)), ("win_rate", models.FloatField(default=0)), ("profit_factor", models.FloatField(default=0)), ("max_drawdown", models.FloatField(default=0)), ("net_pnl", models.FloatField(default=0)), ("snapshot_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("strategy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="performance_snapshots", to="trading.strategy"))], options={"ordering": ["-snapshot_at"]}),
        migrations.CreateModel(name="RiskEvent", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("event_type", models.CharField(db_index=True, max_length=80)), ("severity", models.CharField(choices=[("INFO", "Info"), ("WARNING", "Warning"), ("CRITICAL", "Critical")], db_index=True, default="INFO", max_length=20)), ("message", models.TextField()), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("trade", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="risk_events", to="trading.trade")), ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="ConnectionLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("broker", models.CharField(db_index=True, max_length=60)), ("account_id", models.CharField(blank=True, db_index=True, max_length=80)), ("status", models.CharField(db_index=True, max_length=40)), ("latency_ms", models.FloatField(default=0)), ("message", models.TextField(blank=True)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="PredictionHistory", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("symbol", models.CharField(db_index=True, max_length=20)), ("model_name", models.CharField(db_index=True, max_length=120)), ("prediction", models.JSONField(default=dict)), ("confidence", models.FloatField(default=0)), ("actual_outcome", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="UserPreferences", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("default_symbol", models.CharField(default="R_75", max_length=20)), ("trading_enabled", models.BooleanField(default=False)), ("risk_percent", models.FloatField(default=0.02)), ("max_daily_loss", models.FloatField(default=0)), ("max_exposure", models.FloatField(default=0)), ("notification_preferences", models.JSONField(blank=True, default=dict)), ("updated_at", models.DateTimeField(auto_now=True)), ("default_strategy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="trading.strategy")), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="trading_preferences", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="MarketCandle", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("symbol", models.CharField(max_length=20)), ("timeframe", models.CharField(max_length=10)), ("timestamp", models.DateTimeField()), ("open", models.FloatField()), ("high", models.FloatField()), ("low", models.FloatField()), ("close", models.FloatField()), ("volume", models.FloatField(default=0)), ("source", models.CharField(default="deriv", max_length=60))], options={"ordering": ["timestamp"]}),
        migrations.AddIndex("trade", models.Index(fields=["user", "status", "-opened_at"], name="trading_tra_user_id_0473f3_idx")),
        migrations.AddIndex("trade", models.Index(fields=["symbol", "status"], name="trading_tra_symbol_85335e_idx")),
        migrations.AddConstraint("trade", models.UniqueConstraint(condition=models.Q(("client_request_id", ""), _negated=True), fields=("user", "client_request_id"), name="unique_trade_client_request")),
        migrations.AddIndex("tradeexecution", models.Index(fields=["trade", "-created_at"], name="trading_tra_trade_i_98d44f_idx")),
        migrations.AddIndex("tradeexecution", models.Index(fields=["broker", "status"], name="trading_tra_broker_4998f0_idx")),
        migrations.AddIndex("tradestatetransition", models.Index(fields=["trade", "-created_at"], name="trading_tra_trade_i_d7d1fb_idx")),
        migrations.AddIndex("tradestatetransition", models.Index(fields=["to_state", "-created_at"], name="trading_tra_to_stat_8ac8f5_idx")),
        migrations.AddIndex("portfoliosnapshot", models.Index(fields=["user", "-created_at"], name="trading_por_user_id_d38ce8_idx")),
        migrations.AddIndex("strategyperformance", models.Index(fields=["strategy", "-snapshot_at"], name="trading_str_strateg_decbf7_idx")),
        migrations.AddIndex("strategyperformance", models.Index(fields=["symbol", "-snapshot_at"], name="trading_str_symbol_31f023_idx")),
        migrations.AddIndex("riskevent", models.Index(fields=["event_type", "severity", "-created_at"], name="trading_ris_event_t_c39372_idx")),
        migrations.AddIndex("connectionlog", models.Index(fields=["broker", "status", "-created_at"], name="trading_con_broker_4c0af2_idx")),
        migrations.AddIndex("predictionhistory", models.Index(fields=["symbol", "model_name", "-created_at"], name="trading_pre_symbol_75ed83_idx")),
        migrations.AddIndex("marketcandle", models.Index(fields=["symbol", "timeframe", "timestamp"], name="trading_mar_symbol_7ca63d_idx")),
        migrations.AddConstraint("marketcandle", models.UniqueConstraint(fields=("symbol", "timeframe", "timestamp", "source"), name="unique_market_candle")),
    ]
