# Generated by Django 6.0.8 on 2026-08-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_trading', '0002_signal_symbol_created_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
