# Generated by Django 6.0.6 on 2026-08-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_institutional_trading_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='connectionlog',
            new_name='trading_con_broker_433059_idx',
            old_name='trading_con_broker_4c0af2_idx',
        ),
        migrations.RenameIndex(
            model_name='marketcandle',
            new_name='trading_mar_symbol_d893cf_idx',
            old_name='trading_mar_symbol_7ca63d_idx',
        ),
        migrations.RenameIndex(
            model_name='portfoliosnapshot',
            new_name='trading_por_user_id_d7389a_idx',
            old_name='trading_por_user_id_d38ce8_idx',
        ),
        migrations.RenameIndex(
            model_name='predictionhistory',
            new_name='trading_pre_symbol_748741_idx',
            old_name='trading_pre_symbol_75ed83_idx',
        ),
        migrations.RenameIndex(
            model_name='riskevent',
            new_name='trading_ris_event_t_52a9d3_idx',
            old_name='trading_ris_event_t_c39372_idx',
        ),
        migrations.RenameIndex(
            model_name='strategyperformance',
            new_name='trading_str_strateg_141e06_idx',
            old_name='trading_str_strateg_decbf7_idx',
        ),
        migrations.RenameIndex(
            model_name='strategyperformance',
            new_name='trading_str_symbol_8392ff_idx',
            old_name='trading_str_symbol_31f023_idx',
        ),
        migrations.RenameIndex(
            model_name='trade',
            new_name='trading_tra_user_id_663858_idx',
            old_name='trading_tra_user_id_0473f3_idx',
        ),
        migrations.RenameIndex(
            model_name='trade',
            new_name='trading_tra_symbol_abb7cc_idx',
            old_name='trading_tra_symbol_85335e_idx',
        ),
        migrations.RenameIndex(
            model_name='tradeexecution',
            new_name='trading_tra_trade_i_87c389_idx',
            old_name='trading_tra_trade_i_98d44f_idx',
        ),
        migrations.RenameIndex(
            model_name='tradeexecution',
            new_name='trading_tra_broker_56eedc_idx',
            old_name='trading_tra_broker_4998f0_idx',
        ),
        migrations.RenameIndex(
            model_name='tradestatetransition',
            new_name='trading_tra_trade_i_b83424_idx',
            old_name='trading_tra_trade_i_d7d1fb_idx',
        ),
        migrations.RenameIndex(
            model_name='tradestatetransition',
            new_name='trading_tra_to_stat_75d541_idx',
            old_name='trading_tra_to_stat_8ac8f5_idx',
        ),
    ]
