# Generated by Django 6.0.6 on 2026-08-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_rename_trading_con_broker_4c0af2_idx_trading_con_broker_433059_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='derivaccount',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='derivaccount',
            name='account_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='derivaccount',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='derivaccount',
            name='last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivaccount',
            name='token_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('refreshing', 'Refreshing')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='derivaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='derivaccount',
            name='account_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='derivaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='derivaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deriv_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='derivaccount',
            index=models.Index(fields=['user', '-updated_at'], name='trading_der_user_id_6beba6_idx'),
        ),
        migrations.AddIndex(
            model_name='derivaccount',
            index=models.Index(fields=['account_id', 'token_status'], name='trading_der_account_19b7fe_idx'),
        ),
    ]
