# Generated manually for Phase 13.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Broker', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name', models.CharField(max_length=120, unique=True)),('broker_type', models.CharField(choices=[('deriv','Deriv'),('paper','Paper'),('mt5','Mt5'),('mt4','Mt4'),('oanda','Oanda'),('binance','Binance'),('bybit','Bybit'),('kraken','Kraken'),('interactive_brokers','Interactive Brokers'),('alpaca','Alpaca'),('ctrader','Ctrader'),('dxtrade','Dxtrade'),('tradingview','Tradingview')], db_index=True, max_length=40)),('status', models.CharField(choices=[('active','Active'),('disabled','Disabled'),('maintenance','Maintenance'),('degraded','Degraded'),('offline','Offline')], db_index=True, default='active', max_length=24)),('version', models.CharField(blank=True, max_length=40)),('api_endpoint', models.URLField(blank=True)),('websocket_endpoint', models.URLField(blank=True)),('supports_demo', models.BooleanField(default=True)),('supports_live', models.BooleanField(default=False)),('metadata', models.JSONField(blank=True, default=dict)),('created_at', models.DateTimeField(auto_now_add=True))], options={'ordering':['name']}),
        migrations.CreateModel(name='BrokerAccount', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('account_id', models.CharField(max_length=120)),('currency', models.CharField(default='USD', max_length=12)),('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('equity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('margin', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('free_margin', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('status', models.CharField(default='active', max_length=24)),('is_preferred', models.BooleanField(default=False)),('credentials', models.JSONField(blank=True, default=dict)),('last_synced_at', models.DateTimeField(blank=True, null=True)),('created_at', models.DateTimeField(auto_now_add=True)),('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to='brokers.broker')),('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_broker_accounts', to=settings.AUTH_USER_MODEL))], options={'unique_together':{('broker','account_id')}}),
        migrations.CreateModel(name='BrokerConnection', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('status', models.CharField(default='disconnected', max_length=24)),('latency', models.FloatField(default=0)),('last_ping', models.DateTimeField(blank=True, null=True)),('heartbeat', models.JSONField(blank=True, default=dict)),('connected_at', models.DateTimeField(blank=True, null=True)),('updated_at', models.DateTimeField(auto_now=True)),('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='brokers.broker'))]),
        migrations.CreateModel(name='Order', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('strategy', models.CharField(blank=True, max_length=120)),('symbol', models.CharField(db_index=True, max_length=40)),('direction', models.CharField(max_length=16)),('order_type', models.CharField(default='market', max_length=32)),('contract_type', models.CharField(blank=True, max_length=40)),('stake', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),('status', models.CharField(db_index=True, default='created', max_length=32)),('client_order_id', models.CharField(blank=True, db_index=True, max_length=100)),('broker_order_id', models.CharField(blank=True, db_index=True, max_length=120)),('routing_context', models.JSONField(blank=True, default=dict)),('submitted_at', models.DateTimeField(blank=True, null=True)),('executed_at', models.DateTimeField(blank=True, null=True)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='brokers.brokeraccount')),('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='brokers.broker')),('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_orders', to=settings.AUTH_USER_MODEL))], options={'ordering':['-created_at']}),
        migrations.CreateModel(name='ExecutionReport', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('execution_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),('requested_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),('slippage', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('latency', models.FloatField(default=0)),('fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('status', models.CharField(default='submitted', max_length=32)),('raw_report', models.JSONField(blank=True, default=dict)),('created_at', models.DateTimeField(auto_now_add=True)),('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_reports', to='brokers.order'))]),
        migrations.CreateModel(name='Position', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('symbol', models.CharField(db_index=True, max_length=40)),('direction', models.CharField(max_length=16)),('size', models.DecimalField(decimal_places=8, max_digits=20)),('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('profit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),('status', models.CharField(db_index=True, default='open', max_length=24)),('opened_at', models.DateTimeField(default=django.utils.timezone.now)),('closed_at', models.DateTimeField(blank=True, null=True)),('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='brokers.brokeraccount')),('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='brokers.broker'))]),
        migrations.CreateModel(name='TradeReconciliation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('trade', models.JSONField(blank=True, default=dict)),('matched', models.BooleanField(default=False)),('difference', models.JSONField(blank=True, default=dict)),('repaired', models.BooleanField(default=False)),('timestamp', models.DateTimeField(auto_now_add=True)),('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='brokers.broker'))]),
    ]
