# Generated by Django 6.0.8 on 2026-08-26 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('broker_type', models.CharField(choices=[('deriv', 'Deriv'), ('paper', 'Paper'), ('binance', 'Binance'), ('bybit', 'Bybit'), ('oanda', 'Oanda'), ('interactive_brokers', 'Interactive Brokers'), ('metatrader_gateway', 'Metatrader Gateway'), ('dxtrade', 'Dxtrade'), ('ctrader', 'Ctrader'), ('alpaca', 'Alpaca'), ('forex_com', 'Forex Com'), ('pepperstone', 'Pepperstone'), ('ic_markets', 'Ic Markets'), ('exness', 'Exness'), ('mt5', 'Mt5'), ('mt4', 'Mt4')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('maintenance', 'Maintenance'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('coming_soon', 'Coming Soon')], db_index=True, default='active', max_length=24)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('api_endpoint', models.URLField(blank=True)),
                ('websocket_endpoint', models.URLField(blank=True)),
                ('supports_demo', models.BooleanField(default=True)),
                ('supports_live', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=120)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('free_margin', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('margin_call', 'Margin Call'), ('suspended', 'Suspended')], default='active', max_length=24)),
                ('is_preferred', models.BooleanField(default=False)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('refreshing', 'Refreshing')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_refresh', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to='brokers.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_broker_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('degraded', 'Degraded'), ('failed', 'Failed'), ('reconnecting', 'Reconnecting')], default='disconnected', max_length=24)),
                ('latency', models.FloatField(default=0)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('heartbeat', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='brokers.broker')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('event', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='brokers.brokeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='brokers.broker')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(blank=True, max_length=120)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rise', 'Rise'), ('fall', 'Fall'), ('call', 'Call'), ('put', 'Put')], max_length=16)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('trailing_stop', 'Trailing Stop'), ('bracket', 'Bracket'), ('oco', 'Oco'), ('ioc', 'Ioc'), ('fok', 'Fok'), ('gtc', 'Gtc'), ('day', 'Day'), ('gtd', 'Gtd')], default='market', max_length=32)),
                ('contract_type', models.CharField(blank=True, choices=[('rise_fall', 'Rise Fall'), ('higher_lower', 'Higher Lower'), ('touch_no_touch', 'Touch No Touch'), ('in_out', 'In Out'), ('matches_differs', 'Matches Differs'), ('even_odd', 'Even Odd'), ('accumulators', 'Accumulators'), ('multiplier', 'Multiplier'), ('lookbacks', 'Lookbacks'), ('vanillas', 'Vanillas'), ('turbos', 'Turbos'), ('reset_call', 'Reset Call'), ('reset_put', 'Reset Put')], max_length=40)),
                ('stake', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('approved', 'Approved'), ('queued', 'Queued'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('executed', 'Executed'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('failed', 'Failed'), ('reconciled', 'Reconciled')], db_index=True, default='created', max_length=32)),
                ('client_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('broker_order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('routing_context', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='brokers.brokeraccount')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='brokers.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('slippage', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('latency', models.FloatField(default=0)),
                ('fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('approved', 'Approved'), ('queued', 'Queued'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('executed', 'Executed'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('failed', 'Failed'), ('reconciled', 'Reconciled')], default='submitted', max_length=32)),
                ('raw_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_reports', to='brokers.order')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rise', 'Rise'), ('fall', 'Fall'), ('call', 'Call'), ('put', 'Put')], max_length=16)),
                ('size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(db_index=True, default='open', max_length=24)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='brokers.brokeraccount')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='brokers.broker')),
            ],
        ),
        migrations.CreateModel(
            name='TradeReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.JSONField(blank=True, default=dict)),
                ('matched', models.BooleanField(default=False)),
                ('difference', models.JSONField(blank=True, default=dict)),
                ('repaired', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='brokers.broker')),
            ],
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['user', 'status'], name='brokers_bro_user_id_ace552_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['broker', 'is_preferred'], name='brokers_bro_broker__f29040_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['user', 'token_status'], name='brokers_bro_user_id_1ab670_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokeraccount',
            unique_together={('broker', 'account_id')},
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['broker', 'status'], name='brokers_bro_broker__2b0b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['last_ping'], name='brokers_bro_last_pi_743fac_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnectionlog',
            index=models.Index(fields=['broker_account', '-created_at'], name='brokers_bro_broker__ba4600_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnectionlog',
            index=models.Index(fields=['event'], name='brokers_bro_event_f144cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokerpermission',
            unique_together={('broker', 'permission')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='brokers_ord_user_id_157ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker', 'status'], name='brokers_ord_broker__e4e374_idx'),
        ),
    ]
