# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('margin_call', 'Margin Call'), ('suspended', 'Suspended')], default='active', max_length=24),
        ),
        migrations.AlterField(
            model_name='brokerconnection',
            name='status',
            field=models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('degraded', 'Degraded'), ('failed', 'Failed'), ('reconnecting', 'Reconnecting')], default='disconnected', max_length=24),
        ),
        migrations.AlterField(
            model_name='executionreport',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('approved', 'Approved'), ('queued', 'Queued'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('executed', 'Executed'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('failed', 'Failed'), ('reconciled', 'Reconciled')], default='submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('rise_fall', 'Rise Fall'), ('higher_lower', 'Higher Lower'), ('touch_no_touch', 'Touch No Touch'), ('in_out', 'In Out'), ('matches_differs', 'Matches Differs'), ('even_odd', 'Even Odd'), ('accumulators', 'Accumulators'), ('multiplier', 'Multiplier'), ('lookbacks', 'Lookbacks'), ('vanillas', 'Vanillas'), ('turbos', 'Turbos'), ('reset_call', 'Reset Call'), ('reset_put', 'Reset Put')], max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='direction',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rise', 'Rise'), ('fall', 'Fall'), ('call', 'Call'), ('put', 'Put')], max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('trailing_stop', 'Trailing Stop'), ('bracket', 'Bracket'), ('oco', 'Oco'), ('ioc', 'Ioc'), ('fok', 'Fok'), ('gtc', 'Gtc'), ('day', 'Day'), ('gtd', 'Gtd')], default='market', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('approved', 'Approved'), ('queued', 'Queued'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('executed', 'Executed'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('failed', 'Failed'), ('reconciled', 'Reconciled')], db_index=True, default='created', max_length=32),
        ),
        migrations.AlterField(
            model_name='position',
            name='direction',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rise', 'Rise'), ('fall', 'Fall'), ('call', 'Call'), ('put', 'Put')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['user', 'status'], name='brokers_bro_user_id_ace552_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['broker', 'is_preferred'], name='brokers_bro_broker__f29040_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['broker', 'status'], name='brokers_bro_broker__2b0b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['last_ping'], name='brokers_bro_last_pi_743fac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='brokers_ord_user_id_157ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker', 'status'], name='brokers_ord_broker__e4e374_idx'),
        ),
    ]
