# Generated by Django 6.0.6 on 2026-08-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_alter_brokeraccount_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='broker_type',
            field=models.CharField(choices=[('deriv', 'Deriv'), ('paper', 'Paper'), ('binance', 'Binance'), ('bybit', 'Bybit'), ('oanda', 'Oanda'), ('interactive_brokers', 'Interactive Brokers'), ('metatrader_gateway', 'Metatrader Gateway'), ('dxtrade', 'Dxtrade'), ('ctrader', 'Ctrader'), ('alpaca', 'Alpaca'), ('forex_com', 'Forex Com'), ('pepperstone', 'Pepperstone'), ('ic_markets', 'Ic Markets'), ('exness', 'Exness'), ('mt5', 'Mt5'), ('mt4', 'Mt4')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='broker',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('maintenance', 'Maintenance'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('coming_soon', 'Coming Soon')], db_index=True, default='active', max_length=24),
        ),
    ]
