# Generated by Django 6.0.8 on 2026-08-25 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Trend Following', 'Trend Following'), ('Mean Reversion', 'Mean Reversion'), ('Momentum', 'Momentum'), ('Breakout', 'Breakout'), ('Scalping', 'Scalping'), ('Swing Trading', 'Swing Trading'), ('Range Trading', 'Range Trading'), ('Volatility Trading', 'Volatility Trading'), ('Support & Resistance', 'Support & Resistance'), ('News Trading', 'News Trading'), ('Smart Money Concepts', 'Smart Money Concepts'), ('ICT Concepts', 'ICT Concepts'), ('Liquidity Trading', 'Liquidity Trading'), ('AI Hybrid Strategies', 'AI Hybrid Strategies')], max_length=80)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('author', models.CharField(blank=True, max_length=160)),
                ('lifecycle_state', models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('loaded', 'Loaded'), ('initialized', 'Initialized'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('archived', 'Archived')], db_index=True, default='created', max_length=32)),
                ('module_path', models.CharField(blank=True, max_length=255)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'category'], name='strategies__enabled_aaadb9_idx'), models.Index(fields=['slug', 'version'], name='strategies__slug_e97c02_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrategyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('timeframe', models.CharField(db_index=True, default='M1', max_length=16)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('risk_profile', models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive'), ('custom', 'Custom')], default='balanced', max_length=32)),
                ('schedule', models.CharField(choices=[('continuous', 'Continuous'), ('every_tick', 'Every Tick'), ('every_candle', 'Every Candle'), ('every_minute', 'Every Minute'), ('every_5_minutes', 'Every 5 Minutes'), ('every_15_minutes', 'Every 15 Minutes'), ('hourly', 'Hourly'), ('custom_cron', 'Custom Cron')], default='every_candle', max_length=32)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_configurations', to='brokers.brokeraccount')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('signal', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('STRONG BUY', 'STRONG BUY'), ('STRONG SELL', 'STRONG SELL'), ('HOLD', 'HOLD'), ('EXIT', 'EXIT'), ('REDUCE POSITION', 'REDUCE POSITION'), ('ADD POSITION', 'ADD POSITION')], default='HOLD', max_length=32)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=24)),
                ('latency_ms', models.FloatField(default=0)),
                ('error', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='strategies.strategyconfiguration')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('expectancy', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('signal', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('STRONG BUY', 'STRONG BUY'), ('STRONG SELL', 'STRONG SELL'), ('HOLD', 'HOLD'), ('EXIT', 'EXIT'), ('REDUCE POSITION', 'REDUCE POSITION'), ('ADD POSITION', 'ADD POSITION')], max_length=32)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='strategies.strategyconfiguration')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='strategyconfiguration',
            index=models.Index(fields=['user', 'enabled'], name='strategies__user_id_90ced2_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyconfiguration',
            index=models.Index(fields=['symbol', 'timeframe'], name='strategies__symbol_48d2fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyconfiguration',
            unique_together={('strategy', 'user', 'symbol', 'timeframe')},
        ),
        migrations.AddIndex(
            model_name='strategyexecution',
            index=models.Index(fields=['strategy', 'status'], name='strategies__strateg_47d6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyexecution',
            index=models.Index(fields=['symbol', 'timeframe', '-started_at'], name='strategies__symbol_5d51cd_idx'),
        ),
        migrations.AddIndex(
            model_name='strategysignal',
            index=models.Index(fields=['strategy', 'symbol', '-timestamp'], name='strategies__strateg_802884_idx'),
        ),
    ]
