# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_rename_broker_brok_user_id_3f87ad_idx_broker_brok_user_id_23914c_idx_and_more'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='strategy',
            new_name='strategies__enabled_aaadb9_idx',
            old_name='strategies_s_enabled_51dc7f_idx',
        ),
        migrations.RenameIndex(
            model_name='strategy',
            new_name='strategies__slug_e97c02_idx',
            old_name='strategies_s_slug_4f00a6_idx',
        ),
        migrations.AlterField(
            model_name='strategy',
            name='category',
            field=models.CharField(choices=[('Trend Following', 'Trend Following'), ('Mean Reversion', 'Mean Reversion'), ('Momentum', 'Momentum'), ('Breakout', 'Breakout'), ('Scalping', 'Scalping'), ('Swing Trading', 'Swing Trading'), ('Range Trading', 'Range Trading'), ('Volatility Trading', 'Volatility Trading'), ('Support & Resistance', 'Support & Resistance'), ('News Trading', 'News Trading'), ('Smart Money Concepts', 'Smart Money Concepts'), ('ICT Concepts', 'ICT Concepts'), ('Liquidity Trading', 'Liquidity Trading'), ('AI Hybrid Strategies', 'AI Hybrid Strategies')], max_length=80),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='lifecycle_state',
            field=models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('loaded', 'Loaded'), ('initialized', 'Initialized'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('archived', 'Archived')], db_index=True, default='created', max_length=32),
        ),
        migrations.AlterField(
            model_name='strategyconfiguration',
            name='risk_profile',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive'), ('custom', 'Custom')], default='balanced', max_length=32),
        ),
        migrations.AlterField(
            model_name='strategyconfiguration',
            name='schedule',
            field=models.CharField(choices=[('continuous', 'Continuous'), ('every_tick', 'Every Tick'), ('every_candle', 'Every Candle'), ('every_minute', 'Every Minute'), ('every_5_minutes', 'Every 5 Minutes'), ('every_15_minutes', 'Every 15 Minutes'), ('hourly', 'Hourly'), ('custom_cron', 'Custom Cron')], default='every_candle', max_length=32),
        ),
        migrations.AlterField(
            model_name='strategyexecution',
            name='signal',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('STRONG BUY', 'STRONG BUY'), ('STRONG SELL', 'STRONG SELL'), ('HOLD', 'HOLD'), ('EXIT', 'EXIT'), ('REDUCE POSITION', 'REDUCE POSITION'), ('ADD POSITION', 'ADD POSITION')], default='HOLD', max_length=32),
        ),
        migrations.AlterField(
            model_name='strategyexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='strategysignal',
            name='signal',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('STRONG BUY', 'STRONG BUY'), ('STRONG SELL', 'STRONG SELL'), ('HOLD', 'HOLD'), ('EXIT', 'EXIT'), ('REDUCE POSITION', 'REDUCE POSITION'), ('ADD POSITION', 'ADD POSITION')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='strategyconfiguration',
            index=models.Index(fields=['user', 'enabled'], name='strategies__user_id_90ced2_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyconfiguration',
            index=models.Index(fields=['symbol', 'timeframe'], name='strategies__symbol_48d2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyexecution',
            index=models.Index(fields=['strategy', 'status'], name='strategies__strateg_47d6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyexecution',
            index=models.Index(fields=['symbol', 'timeframe', '-started_at'], name='strategies__symbol_5d51cd_idx'),
        ),
        migrations.AddIndex(
            model_name='strategysignal',
            index=models.Index(fields=['strategy', 'symbol', '-timestamp'], name='strategies__strateg_802884_idx'),
        ),
    ]
