from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='SignalProvider', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('display_name',models.CharField(max_length=120)),('bio',models.TextField(blank=True)),('verification_status',models.CharField(default='pending',max_length=32)),('experience_level',models.CharField(blank=True,max_length=32)),('country',models.CharField(blank=True,max_length=80)),('followers',models.PositiveIntegerField(default=0)),('rating',models.FloatField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='signal_provider_profiles',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='TradingStrategy', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('description',models.TextField(blank=True)),('category',models.CharField(max_length=40)),('risk_level',models.CharField(default='medium',max_length=32)),('subscription_price',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('visibility',models.CharField(default='public',max_length=32)),('performance_score',models.FloatField(default=0)),('provider',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='strategies',to='copy_trading.signalprovider'))]),
        migrations.CreateModel(name='StrategySubscription', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(default='active',max_length=32)),('started_at',models.DateTimeField(auto_now_add=True)),('expires_at',models.DateTimeField(blank=True,null=True)),('follower',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='strategy_subscriptions',to=settings.AUTH_USER_MODEL)),('strategy',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='subscriptions',to='copy_trading.tradingstrategy'))]),
        migrations.CreateModel(name='TradeMirror', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('provider_trade',models.CharField(max_length=120)),('follower_trade',models.CharField(blank=True,max_length=120)),('allocation',models.DecimalField(decimal_places=4,default=1,max_digits=10)),('multiplier',models.DecimalField(decimal_places=4,default=1,max_digits=10)),('status',models.CharField(default='pending',max_length=32))]),
        migrations.CreateModel(name='RevenueShare', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('amount',models.DecimalField(decimal_places=2,max_digits=12)),('commission',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('paid_at',models.DateTimeField(blank=True,null=True)),('provider',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='copy_trading.signalprovider')),('subscriber',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='PerformanceSnapshot', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('daily_return',models.FloatField(default=0)),('monthly_return',models.FloatField(default=0)),('yearly_return',models.FloatField(default=0)),('drawdown',models.FloatField(default=0)),('sharpe',models.FloatField(default=0)),('profit_factor',models.FloatField(default=0)),('win_rate',models.FloatField(default=0)),('strategy',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='performance_snapshots',to='copy_trading.tradingstrategy'))]),
        migrations.CreateModel(name='Leaderboard', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('ranking',models.PositiveIntegerField()),('score',models.FloatField(default=0)),('period',models.CharField(default='monthly',max_length=32)),('provider',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='copy_trading.signalprovider')),('strategy',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='copy_trading.tradingstrategy'))]),
    ]
