# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingstrategy',
            name='category',
            field=models.CharField(choices=[('forex', 'Forex'), ('synthetic_indices', 'Synthetic_Indices'), ('volatility_indices', 'Volatility_Indices'), ('crypto', 'Crypto'), ('stocks', 'Stocks'), ('indices', 'Indices'), ('commodities', 'Commodities'), ('options', 'Options'), ('multipliers', 'Multipliers'), ('accumulators', 'Accumulators')], max_length=40),
        ),
    ]
