# Generated by Django 6.0.6 on 2026-08-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0002_alter_tradingstrategy_category'),
        ('copy_trading', '0002_copy_execution_models'),
    ]

    operations = [
    ]
