from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='Tenant', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('slug',models.SlugField(unique=True)),('status',models.CharField(default='trial',max_length=32)),('timezone',models.CharField(default='UTC',max_length=64)),('currency',models.CharField(default='USD',max_length=3)),('created_at',models.DateTimeField(auto_now_add=True)),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='owned_tenants',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Organization', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('industry',models.CharField(blank=True,max_length=120)),('country',models.CharField(blank=True,max_length=80)),('website',models.URLField(blank=True)),('logo',models.URLField(blank=True)),('status',models.CharField(default='active',max_length=32)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='organizations',to='tenants.tenant'))]),
        migrations.CreateModel(name='Workspace', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('environment',models.CharField(default='production',max_length=32)),('default_broker',models.CharField(blank=True,max_length=80)),('timezone',models.CharField(default='UTC',max_length=64)),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='workspaces',to='tenants.organization'))]),
        migrations.CreateModel(name='Subscription', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('plan',models.CharField(default='free',max_length=32)),('status',models.CharField(default='trial',max_length=32)),('billing_cycle',models.CharField(default='monthly',max_length=32)),('price',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('renewal_date',models.DateField(blank=True,null=True)),('trial_end',models.DateTimeField(blank=True,null=True)),('tenant',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='subscription',to='tenants.tenant'))]),
        migrations.CreateModel(name='License', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('license_key',models.CharField(max_length=80,unique=True)),('max_users',models.PositiveIntegerField(default=1)),('max_brokers',models.PositiveIntegerField(default=1)),('max_strategies',models.PositiveIntegerField(default=1)),('expires_at',models.DateTimeField(blank=True,null=True)),('subscription',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='license',to='tenants.subscription'))]),
        migrations.CreateModel(name='Team', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('description',models.TextField(blank=True)),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='teams',to='tenants.organization'))]),
        migrations.CreateModel(name='TeamMember', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(max_length=32)),('joined_at',models.DateTimeField(auto_now_add=True)),('team',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='members',to='tenants.team')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='FeatureFlag', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('feature',models.CharField(max_length=64)),('enabled',models.BooleanField(default=False)),('plan',models.CharField(blank=True,max_length=32)),('tenant',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='feature_flags',to='tenants.tenant'))]),
        migrations.CreateModel(name='UsageMetric', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('metric',models.CharField(max_length=64)),('usage',models.BigIntegerField(default=0)),('quota',models.BigIntegerField(default=0)),('period',models.CharField(default='monthly',max_length=32)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='usage_metrics',to='tenants.tenant'))]),
        migrations.CreateModel(name='WhiteLabelSettings', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('brand_name',models.CharField(blank=True,max_length=120)),('logo',models.URLField(blank=True)),('custom_domain',models.CharField(blank=True,max_length=255)),('colors',models.JSONField(blank=True,default=dict)),('email_templates',models.JSONField(blank=True,default=dict)),('tenant',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='branding',to='tenants.tenant'))]),
        migrations.AlterUniqueTogether(name='organization',unique_together={('tenant','name')}), migrations.AlterUniqueTogether(name='teammember',unique_together={('team','user')}), migrations.AlterUniqueTogether(name='usagemetric',unique_together={('tenant','metric','period')}),
    ]
