# Generated by Django 6.0.8 on 2026-08-25 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('status', models.CharField(default='active', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='free', max_length=32)),
                ('status', models.CharField(default='trial', max_length=32)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime'), ('custom_enterprise', 'Custom_Enterprise')], default='monthly', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=80, unique=True)),
                ('max_users', models.PositiveIntegerField(default=1)),
                ('max_brokers', models.PositiveIntegerField(default=1)),
                ('max_strategies', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='tenants.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tenants.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past_Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=32)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('ai_engine', 'Ai Engine'), ('copy_trading', 'Copy Trading'), ('api_access', 'Api Access'), ('paper_trading', 'Paper Trading'), ('backtesting', 'Backtesting'), ('monitoring', 'Monitoring'), ('portfolio_analytics', 'Portfolio Analytics'), ('multi_broker', 'Multi Broker'), ('white_label', 'White Label'), ('custom_branding', 'Custom Branding')], max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('plan', models.CharField(blank=True, max_length=32)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('api_calls', 'Api Calls'), ('trades', 'Trades'), ('strategies', 'Strategies'), ('ai_predictions', 'Ai Predictions'), ('broker_connections', 'Broker Connections'), ('notifications', 'Notifications'), ('storage', 'Storage'), ('bandwidth', 'Bandwidth'), ('users', 'Users'), ('reports', 'Reports'), ('automations', 'Automations')], max_length=64)),
                ('usage', models.BigIntegerField(default=0)),
                ('quota', models.BigIntegerField(default=0)),
                ('period', models.CharField(default='monthly', max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteLabelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('logo', models.URLField(blank=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255)),
                ('colors', models.JSONField(blank=True, default=dict)),
                ('email_templates', models.JSONField(blank=True, default=dict)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('environment', models.CharField(default='production', max_length=32)),
                ('default_broker', models.CharField(blank=True, max_length=80)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='tenants.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('platform_owner', 'Platform_Owner'), ('organization_owner', 'Organization_Owner'), ('administrator', 'Administrator'), ('manager', 'Manager'), ('trader', 'Trader'), ('analyst', 'Analyst'), ('developer', 'Developer'), ('support', 'Support'), ('auditor', 'Auditor'), ('viewer', 'Viewer')], max_length=32)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug', 'status'], name='tenants_ten_slug_2439c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='usagemetric',
            unique_together={('tenant', 'metric', 'period')},
        ),
    ]
