# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='feature',
            field=models.CharField(choices=[('ai_engine', 'Ai Engine'), ('copy_trading', 'Copy Trading'), ('api_access', 'Api Access'), ('paper_trading', 'Paper Trading'), ('backtesting', 'Backtesting'), ('monitoring', 'Monitoring'), ('portfolio_analytics', 'Portfolio Analytics'), ('multi_broker', 'Multi Broker'), ('white_label', 'White Label'), ('custom_branding', 'Custom Branding')], max_length=64),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime'), ('custom_enterprise', 'Custom_Enterprise')], default='monthly', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='free', max_length=32),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('platform_owner', 'Platform_Owner'), ('organization_owner', 'Organization_Owner'), ('administrator', 'Administrator'), ('manager', 'Manager'), ('trader', 'Trader'), ('analyst', 'Analyst'), ('developer', 'Developer'), ('support', 'Support'), ('auditor', 'Auditor'), ('viewer', 'Viewer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past_Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=32),
        ),
        migrations.AlterField(
            model_name='usagemetric',
            name='metric',
            field=models.CharField(choices=[('api_calls', 'Api Calls'), ('trades', 'Trades'), ('strategies', 'Strategies'), ('ai_predictions', 'Ai Predictions'), ('broker_connections', 'Broker Connections'), ('notifications', 'Notifications'), ('storage', 'Storage'), ('bandwidth', 'Bandwidth'), ('users', 'Users'), ('reports', 'Reports'), ('automations', 'Automations')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug', 'status'], name='tenants_ten_slug_2439c1_idx'),
        ),
    ]
