# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='indicatorvalue',
            new_name='indicators__symbol_d47630_idx',
            old_name='indicators__symbol_2ef450_idx',
        ),
    ]
