# Generated by Django 6.0.8 on 2026-08-26 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(db_index=True, max_length=160)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('mode', models.CharField(default='candle_close', max_length=32)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestClusterJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('worker_id', models.CharField(blank=True, max_length=120)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_jobs', to='backtesting.backtest')),
            ],
        ),
        migrations.CreateModel(
            name='BacktestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_profit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('gross_profit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('gross_loss', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('expectancy', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('win_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('loss_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('sharpe', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('sortino', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('calmar', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('monthly_returns', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='backtesting.backtest')),
            ],
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=12)),
                ('profit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('fees', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtesting.backtest')),
            ],
            options={
                'ordering': ['entry_time'],
            },
        ),
        migrations.AddIndex(
            model_name='backtest',
            index=models.Index(fields=['user', 'status'], name='backtesting_user_id_3c0d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='backtest',
            index=models.Index(fields=['symbol', 'timeframe'], name='backtesting_symbol_252400_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['backtest', 'entry_time'], name='backtesting_backtes_a64aea_idx'),
        ),
    ]
