# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflow',
            new_name='automation__user_id_dd9362_idx',
            old_name='automation__user_id_94d532_idx',
        ),
    ]
