from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import BrokerViewSet, BrokerAccountViewSet, BrokerConnectionViewSet, BrokerOrderViewSet, ExecutionReportViewSet, PositionViewSet, TradeReconciliationViewSet, BrokerHealthViewSet, connect_broker, disconnect_broker

router = DefaultRouter()
router.register('brokers', BrokerViewSet, basename='brokers')
router.register('brokers/accounts', BrokerAccountViewSet, basename='broker-accounts')
router.register('brokers/connections', BrokerConnectionViewSet, basename='broker-connections')
router.register('orders', BrokerOrderViewSet, basename='broker-orders')
router.register('executions', ExecutionReportViewSet, basename='executions')
router.register('positions', PositionViewSet, basename='broker-positions')
router.register('reconciliation', TradeReconciliationViewSet, basename='reconciliation')
router.register('broker-health', BrokerHealthViewSet, basename='broker-health')

# The explicit nested routes must precede the generic /brokers/<pk>/ route
# generated by the router, otherwise "accounts" is interpreted as a broker id.
urlpatterns = [
    path('brokers/connect/', connect_broker, name='broker-connect'),
    path('brokers/disconnect/', disconnect_broker, name='broker-disconnect'),
    path('brokers/accounts/', BrokerAccountViewSet.as_view({'get': 'list', 'post': 'create'}), name='broker-accounts-list'),
    path('brokers/accounts/<int:pk>/', BrokerAccountViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='broker-accounts-detail'),
] + router.urls
