# Generated by Django 6.0.8 on 2026-08-26 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('span_id', models.CharField(db_index=True, max_length=64)),
                ('parent_span_id', models.CharField(blank=True, max_length=64)),
                ('operation', models.CharField(db_index=True, max_length=160)),
                ('module', models.CharField(db_index=True, max_length=120)),
                ('duration_ms', models.FloatField(default=0)),
                ('status', models.CharField(default='ok', max_length=30)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('category', models.CharField(choices=[('Broker', 'Broker'), ('Trading', 'Trading'), ('Risk', 'Risk'), ('AI', 'AI'), ('Strategy', 'Strategy'), ('Infrastructure', 'Infrastructure'), ('Security', 'Security'), ('Database', 'Database'), ('Performance', 'Performance'), ('Network', 'Network')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL'), ('EMERGENCY', 'EMERGENCY')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'open'), ('acknowledged', 'acknowledged'), ('resolved', 'resolved'), ('suppressed', 'suppressed')], db_index=True, default='open', max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(db_index=True, max_length=160)),
                ('acknowledged', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'status', '-created_at'], name='monitoring__severit_c7ec34_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('module', models.CharField(db_index=True, max_length=120)),
                ('resource', models.CharField(blank=True, max_length=220)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BrokerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(db_index=True, max_length=120)),
                ('connection_status', models.CharField(db_index=True, default='unknown', max_length=40)),
                ('latency', models.FloatField(default=0)),
                ('websocket_status', models.CharField(default='unknown', max_length=40)),
                ('api_status', models.CharField(default='unknown', max_length=40)),
                ('packet_loss', models.FloatField(default=0)),
                ('reconnect_attempts', models.PositiveIntegerField(default=0)),
                ('authorization_status', models.CharField(default='unknown', max_length=40)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('trade_success_rate', models.FloatField(default=0)),
                ('order_latency', models.FloatField(default=0)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('last_trade', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['broker', '-timestamp'], name='monitoring__broker_1f010b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL'), ('EMERGENCY', 'EMERGENCY')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'open'), ('investigating', 'investigating'), ('acknowledged', 'acknowledged'), ('resolved', 'resolved'), ('postmortem', 'postmortem')], db_index=True, default='open', max_length=30)),
                ('root_cause', models.TextField(blank=True)),
                ('postmortem', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='monitoring.alert')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('application', 'application'), ('trading', 'trading'), ('broker', 'broker'), ('ai', 'ai'), ('risk', 'risk'), ('strategy', 'strategy'), ('security', 'security'), ('authentication', 'authentication'), ('api', 'api'), ('database', 'database'), ('celery', 'celery'), ('system', 'system'), ('infrastructure', 'infrastructure')], db_index=True, max_length=40)),
                ('level', models.CharField(db_index=True, default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, db_index=True, max_length=160)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stream', 'level', '-timestamp'], name='monitoring__stream_96970c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=160)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('module', models.CharField(db_index=True, max_length=120)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', 'module', '-timestamp'], name='monitoring__metric__58ea5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('healthy', 'healthy'), ('degraded', 'degraded'), ('down', 'down'), ('unknown', 'unknown')], db_index=True, default='unknown', max_length=20)),
                ('cpu', models.FloatField(default=0)),
                ('memory', models.FloatField(default=0)),
                ('disk', models.FloatField(default=0)),
                ('network', models.FloatField(default=0)),
                ('response_time', models.FloatField(default=0, help_text='Response time in milliseconds')),
                ('uptime', models.FloatField(default=0, help_text='Uptime in seconds')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service_name', '-timestamp'], name='monitoring__service_1cb25d_idx'), models.Index(fields=['status', '-timestamp'], name='monitoring__status_30241a_idx')],
            },
        ),
    ]
