# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status', '-created_at'], name='monitoring__severit_c7ec34_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerhealth',
            index=models.Index(fields=['broker', '-timestamp'], name='monitoring__broker_1f010b_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['stream', 'level', '-timestamp'], name='monitoring__stream_96970c_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['metric_name', 'module', '-timestamp'], name='monitoring__metric__58ea5b_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealth',
            index=models.Index(fields=['service_name', '-timestamp'], name='monitoring__service_1cb25d_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealth',
            index=models.Index(fields=['status', '-timestamp'], name='monitoring__status_30241a_idx'),
        ),
    ]
