# Generated by Django 6.0.8 on 2026-08-26 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='deriv', max_length=80)),
                ('symbol', models.CharField(db_index=True, max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('market', models.CharField(choices=[('Volatility Indices', 'Volatility Indices'), ('Boom', 'Boom'), ('Crash', 'Crash'), ('Forex', 'Forex'), ('Crypto', 'Crypto'), ('Derived Indices', 'Derived Indices'), ('Jump Indices', 'Jump Indices'), ('Commodities', 'Commodities'), ('Stock Indices', 'Stock Indices')], db_index=True, max_length=80)),
                ('sub_market', models.CharField(blank=True, db_index=True, max_length=120)),
                ('pip_size', models.PositiveSmallIntegerField(default=2)),
                ('tick_size', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_tradable', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['market', 'symbol'],
                'indexes': [models.Index(fields=['broker', 'symbol'], name='market_data_broker_263b73_idx'), models.Index(fields=['market', 'sub_market'], name='market_data_market_44d375_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('spread', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('change', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='market_data.marketsymbol')),
            ],
        ),
        migrations.CreateModel(
            name='MarketStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_spread', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('highest_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('lowest_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('highest_volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tick_count', models.PositiveBigIntegerField(default=0)),
                ('average_tick_rate', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('market_volatility', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('average_volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tick_frequency', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='market_data.marketsymbol')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', '-created_at'], name='market_data_symbol__59d0ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('tick', 'tick'), ('1s', '1s'), ('5s', '5s'), ('15s', '15s'), ('30s', '30s'), ('1m', '1m'), ('2m', '2m'), ('5m', '5m'), ('10m', '10m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], db_index=True, max_length=8)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('epoch', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market_data.marketsymbol')),
            ],
            options={
                'ordering': ['-epoch'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-epoch'], name='market_data_symbol__b31767_idx')],
                'unique_together': {('symbol', 'timeframe', 'epoch')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('tick', 'tick'), ('1s', '1s'), ('5s', '5s'), ('15s', '15s'), ('30s', '30s'), ('1m', '1m'), ('2m', '2m'), ('5m', '5m'), ('10m', '10m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], default='tick', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='market_data.marketsymbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symbol', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quote', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('epoch', models.BigIntegerField(db_index=True)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='market_data.marketsymbol')),
            ],
            options={
                'ordering': ['-epoch'],
                'indexes': [models.Index(fields=['symbol', '-epoch'], name='market_data_symbol__33ff45_idx'), models.Index(fields=['received_at'], name='market_data_receive_dec55a_idx')],
                'unique_together': {('symbol', 'epoch', 'quote')},
            },
        ),
    ]
