# Generated by Django 6.0.8 on 2026-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candle',
            new_name='market_data_symbol__b31767_idx',
            old_name='market_data_symbol_9c4a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='marketstatistics',
            new_name='market_data_symbol__59d0ba_idx',
            old_name='market_data_symbol_1d4c8e_idx',
        ),
        migrations.RenameIndex(
            model_name='marketsymbol',
            new_name='market_data_broker_263b73_idx',
            old_name='market_data_broker_7a0a9c_idx',
        ),
        migrations.RenameIndex(
            model_name='marketsymbol',
            new_name='market_data_market_44d375_idx',
            old_name='market_data_market_4f7b32_idx',
        ),
        migrations.RenameIndex(
            model_name='tick',
            new_name='market_data_symbol__33ff45_idx',
            old_name='market_data_symbol_2a3d5b_idx',
        ),
        migrations.RenameIndex(
            model_name='tick',
            new_name='market_data_receive_dec55a_idx',
            old_name='market_data_receive_2c8a1d_idx',
        ),
        migrations.AlterField(
            model_name='candle',
            name='timeframe',
            field=models.CharField(choices=[('tick', 'tick'), ('1s', '1s'), ('5s', '5s'), ('15s', '15s'), ('30s', '30s'), ('1m', '1m'), ('2m', '2m'), ('5m', '5m'), ('10m', '10m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='marketsymbol',
            name='market',
            field=models.CharField(choices=[('Volatility Indices', 'Volatility Indices'), ('Boom', 'Boom'), ('Crash', 'Crash'), ('Forex', 'Forex'), ('Crypto', 'Crypto'), ('Derived Indices', 'Derived Indices'), ('Jump Indices', 'Jump Indices'), ('Commodities', 'Commodities'), ('Stock Indices', 'Stock Indices')], db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='timeframe',
            field=models.CharField(choices=[('tick', 'tick'), ('1s', '1s'), ('5s', '5s'), ('15s', '15s'), ('30s', '30s'), ('1m', '1m'), ('2m', '2m'), ('5m', '5m'), ('10m', '10m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], default='tick', max_length=8),
        ),
    ]
