# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candle',
            name='unique_candle_symbol_timeframe_epoch',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_market_subscription',
        ),
        migrations.RemoveConstraint(
            model_name='tick',
            name='unique_tick_symbol_epoch_quote',
        ),
        migrations.AlterField(
            model_name='candle',
            name='timeframe',
            field=models.CharField(choices=[('tick', 'tick'), ('1s', '1s'), ('5s', '5s'), ('15s', '15s'), ('30s', '30s'), ('1m', '1m'), ('2m', '2m'), ('5m', '5m'), ('10m', '10m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='marketsymbol',
            name='market',
            field=models.CharField(choices=[('Volatility Indices', 'Volatility Indices'), ('Boom', 'Boom'), ('Crash', 'Crash'), ('Forex', 'Forex'), ('Crypto', 'Crypto'), ('Derived Indices', 'Derived Indices'), ('Jump Indices', 'Jump Indices'), ('Commodities', 'Commodities'), ('Stock Indices', 'Stock Indices')], db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='timeframe',
            field=models.CharField(choices=[('tick', 'tick'), ('1s', '1s'), ('5s', '5s'), ('15s', '15s'), ('30s', '30s'), ('1m', '1m'), ('2m', '2m'), ('5m', '5m'), ('10m', '10m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], default='tick', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together={('symbol', 'timeframe', 'epoch')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'symbol', 'timeframe')},
        ),
        migrations.AlterUniqueTogether(
            name='tick',
            unique_together={('symbol', 'epoch', 'quote')},
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(fields=['symbol', 'timeframe', '-epoch'], name='market_data_symbol__b31767_idx'),
        ),
        migrations.AddIndex(
            model_name='marketstatistics',
            index=models.Index(fields=['symbol', '-created_at'], name='market_data_symbol__59d0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsymbol',
            index=models.Index(fields=['broker', 'symbol'], name='market_data_broker_263b73_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsymbol',
            index=models.Index(fields=['market', 'sub_market'], name='market_data_market_44d375_idx'),
        ),
        migrations.AddIndex(
            model_name='tick',
            index=models.Index(fields=['symbol', '-epoch'], name='market_data_symbol__33ff45_idx'),
        ),
        migrations.AddIndex(
            model_name='tick',
            index=models.Index(fields=['received_at'], name='market_data_receive_dec55a_idx'),
        ),
    ]
