# Generated by Django 6.0.8 on 2026-08-26 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=100000, max_digits=18)),
                ('equity', models.DecimalField(decimal_places=8, default=100000, max_digits=18)),
                ('margin', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('free_margin', models.DecimalField(decimal_places=8, default=100000, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=160)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('entry', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('profit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('status', models.CharField(db_index=True, default='open', max_length=24)),
                ('execution_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('paper_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='paper_trading.paperaccount')),
            ],
        ),
    ]
