"""Broker and third-party provider settings."""

from .utils import env

TELEGRAM_BOT_TOKEN = env("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = env("TELEGRAM_CHAT_ID", "")
PAYMENT_PROVIDER = env("PAYMENT_PROVIDER", "intasend").lower()
PAYMENT_HTTP_TIMEOUT = int(env("PAYMENT_HTTP_TIMEOUT", "20"))

# IntaSend (Kenya / KES / M-Pesa + card)
INTASEND_PUBLIC_KEY = env("INTASEND_PUBLIC_KEY", "")
INTASEND_SECRET_KEY = env("INTASEND_SECRET_KEY", "")
INTASEND_WEBHOOK_CHALLENGE = env("INTASEND_WEBHOOK_CHALLENGE", "")
INTASEND_API_BASE_URL = env("INTASEND_API_BASE_URL", "https://api.intasend.com")

# Pesapal API 3.0
PESAPAL_CONSUMER_KEY = env("PESAPAL_CONSUMER_KEY", "")
PESAPAL_CONSUMER_SECRET = env("PESAPAL_CONSUMER_SECRET", "")
PESAPAL_NOTIFICATION_ID = env("PESAPAL_NOTIFICATION_ID", "")
PESAPAL_API_BASE_URL = env("PESAPAL_API_BASE_URL", "https://pay.pesapal.com/v3")

BROKER_APP_ID = env("BROKER_APP_ID", env("DERIV_APP_ID", env("DERIV_OAUTH_CLIENT_ID", "")))
BROKER_WS_URL = env("BROKER_WS_URL", "")
BROKER_OAUTH_CLIENT_ID = env("BROKER_OAUTH_CLIENT_ID", BROKER_APP_ID)
BROKER_REDIRECT_URI = env("BROKER_REDIRECT_URI", "")
