from abc import ABC, abstractmethod
class BrokerAdapter(ABC):
    broker_type='base'
    def __init__(self, broker=None, account=None, credentials=None): self.broker=broker; self.account=account; self.credentials=credentials or {}
    @abstractmethod
    async def connect(self): ...
    @abstractmethod
    async def disconnect(self): ...
    @abstractmethod
    async def authenticate(self): ...
    @abstractmethod
    async def heartbeat(self): ...
    @abstractmethod
    async def get_accounts(self): ...
    @abstractmethod
    async def get_balance(self): ...
    @abstractmethod
    async def get_positions(self): ...
    @abstractmethod
    async def get_orders(self): ...
    @abstractmethod
    async def place_order(self, order): ...
    @abstractmethod
    async def modify_order(self, order, **changes): ...
    @abstractmethod
    async def cancel_order(self, order): ...
    @abstractmethod
    async def close_position(self, position): ...
    @abstractmethod
    async def get_history(self, **filters): ...
    @abstractmethod
    async def subscribe_ticks(self, symbol, callback=None): ...
    @abstractmethod
    async def subscribe_candles(self, symbol, callback=None): ...
    @abstractmethod
    async def subscribe_account(self, callback=None): ...
    @abstractmethod
    async def subscribe_positions(self, callback=None): ...
    @abstractmethod
    async def ping(self): ...
