"""Broker abstraction contract for every execution provider.

Trading, portfolio, risk, analytics, AI, automation, and notification code must
only depend on :class:`BrokerAdapter`; vendor APIs belong in adapter modules.
"""
from abc import ABC, abstractmethod


class BrokerAdapter(ABC):
    broker_type = "base"
    authentication_type = "broker_specific"
    supports_streaming = False
    asset_classes = ()

    def __init__(self, broker=None, account=None, credentials=None):
        self.broker = broker
        self.account = account
        self.credentials = credentials or {}

    @abstractmethod
    async def connect(self): ...
    @abstractmethod
    async def disconnect(self): ...
    @abstractmethod
    async def authenticate(self): ...
    @abstractmethod
    async def refresh_token(self): ...
    @abstractmethod
    async def get_accounts(self): ...
    @abstractmethod
    async def get_balance(self): ...
    @abstractmethod
    async def get_positions(self): ...
    @abstractmethod
    async def get_orders(self): ...
    @abstractmethod
    async def get_open_orders(self): ...
    @abstractmethod
    async def get_trade_history(self, **filters): ...
    @abstractmethod
    async def get_market_data(self, symbol, **params): ...
    @abstractmethod
    async def subscribe_ticks(self, symbol, callback=None): ...
    @abstractmethod
    async def place_order(self, order): ...
    @abstractmethod
    async def modify_order(self, order, **changes): ...
    @abstractmethod
    async def cancel_order(self, order): ...
    @abstractmethod
    async def close_position(self, position): ...
    @abstractmethod
    async def stream_positions(self, callback=None): ...
    @abstractmethod
    async def stream_orders(self, callback=None): ...
    @abstractmethod
    async def stream_prices(self, symbols, callback=None): ...
    @abstractmethod
    async def health_check(self): ...
    @abstractmethod
    async def ping(self): ...

    # Backward-compatible aliases during platform migration.
    async def heartbeat(self): return await self.health_check()
    async def get_history(self, **filters): return await self.get_trade_history(**filters)
    async def subscribe_candles(self, symbol, callback=None): return await self.get_market_data(symbol, timeframe="candles")
    async def subscribe_account(self, callback=None): return await self.stream_orders(callback=callback)
    async def subscribe_positions(self, callback=None): return await self.stream_positions(callback=callback)
