# Generated by Django 6.0.8 on 2026-08-26 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FairValueGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=12)),
                ('bullish', models.BooleanField(default=False)),
                ('bearish', models.BooleanField(default=False)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filled', models.BooleanField(default=False)),
                ('fill_percentage', models.FloatField(default=0)),
                ('strength', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalBias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=12)),
                ('bias', models.CharField(max_length=40)),
                ('confidence', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LiquiditySweep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=12)),
                ('direction', models.CharField(max_length=20)),
                ('swept_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reversal', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=12)),
                ('type', models.CharField(max_length=40)),
                ('internal', models.BooleanField(default=False)),
                ('external', models.BooleanField(default=False)),
                ('equal_high', models.BooleanField(default=False)),
                ('equal_low', models.BooleanField(default=False)),
                ('strength', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumDiscountZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('equilibrium', models.DecimalField(decimal_places=8, max_digits=20)),
                ('premium', models.DecimalField(decimal_places=8, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('volatility', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarketStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=12)),
                ('trend', models.CharField(max_length=40)),
                ('bos_count', models.PositiveIntegerField(default=0)),
                ('choch_count', models.PositiveIntegerField(default=0)),
                ('mss_count', models.PositiveIntegerField(default=0)),
                ('structure_strength', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-timestamp'], name='smart_money_symbol_19099d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=12)),
                ('type', models.CharField(max_length=40)),
                ('bullish', models.BooleanField(default=False)),
                ('bearish', models.BooleanField(default=False)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('mitigated', models.BooleanField(default=False)),
                ('broken', models.BooleanField(default=False)),
                ('strength', models.FloatField(default=0)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'mitigated', 'broken'], name='smart_money_symbol_00e5a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MitigationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retested', models.BooleanField(default=False)),
                ('status', models.CharField(default='first_touch', max_length=32)),
                ('order_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='smart_money.orderblock')),
            ],
        ),
        migrations.CreateModel(
            name='BreakerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=16)),
                ('strength', models.FloatField(default=0)),
                ('status', models.CharField(default='confirmed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakers', to='smart_money.orderblock')),
            ],
        ),
    ]
