# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_money', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketstructure',
            index=models.Index(fields=['symbol', 'timeframe', '-timestamp'], name='smart_money_symbol_19099d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderblock',
            index=models.Index(fields=['symbol', 'timeframe', 'mitigated', 'broken'], name='smart_money_symbol_00e5a7_idx'),
        ),
    ]
