# Generated by Django 6.0.8 on 2026-08-26 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('initial_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('current_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('net_asset_value', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], db_index=True, default='active', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('withdrawal', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('taxes', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('flow_type', models.CharField(default='adjustment', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('syncing', 'Syncing')], default='active', max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_accounts', to='brokers.broker')),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_links', to='brokers.brokeraccount')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(blank=True, db_index=True, max_length=160)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=40)),
                ('allocation_percent', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('allocated_capital', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('risk_budget', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(blank=True, db_index=True, max_length=80)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=40)),
                ('strategy', models.CharField(blank=True, db_index=True, max_length=160)),
                ('exposure', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('risk', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_period', models.CharField(max_length=40)),
                ('expected_return', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('expected_drawdown', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('confidence', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_return', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('weekly_return', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('monthly_return', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('yearly_return', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('cumulative_return', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('drawdown', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('sharpe', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('sortino', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'status'], name='portfolio_p_user_id_59c37a_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['currency', 'status'], name='portfolio_p_currenc_6ca56d_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioaccount',
            index=models.Index(fields=['portfolio', 'status'], name='portfolio_p_portfol_3cc6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioaccount',
            index=models.Index(fields=['broker', 'currency'], name='portfolio_p_broker__0e3b2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioaccount',
            unique_together={('portfolio', 'broker_account')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolioallocation',
            unique_together={('portfolio', 'strategy', 'symbol')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolioexposure',
            unique_together={('portfolio', 'market', 'symbol', 'strategy')},
        ),
        migrations.AddIndex(
            model_name='portfolioperformance',
            index=models.Index(fields=['portfolio', 'timestamp'], name='portfolio_p_portfol_812bd9_idx'),
        ),
    ]
