# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_rename_broker_brok_user_id_3f87ad_idx_broker_brok_user_id_23914c_idx_and_more'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioaccount',
            unique_together={('portfolio', 'broker_account')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolioallocation',
            unique_together={('portfolio', 'strategy', 'symbol')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolioexposure',
            unique_together={('portfolio', 'market', 'symbol', 'strategy')},
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'status'], name='portfolio_p_user_id_59c37a_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['currency', 'status'], name='portfolio_p_currenc_6ca56d_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioaccount',
            index=models.Index(fields=['portfolio', 'status'], name='portfolio_p_portfol_3cc6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioaccount',
            index=models.Index(fields=['broker', 'currency'], name='portfolio_p_broker__0e3b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioperformance',
            index=models.Index(fields=['portfolio', 'timestamp'], name='portfolio_p_portfol_812bd9_idx'),
        ),
    ]
