# Generated by Django 6.0.8 on 2026-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('role', models.CharField(max_length=80)),
                ('status', models.CharField(default='idle', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_status', models.CharField(default='operational', max_length=32)),
                ('market_regime', models.CharField(default='neutral', max_length=40)),
                ('risk_level', models.CharField(default='normal', max_length=32)),
                ('ai_mode', models.CharField(default='supervised', max_length=32)),
                ('health_score', models.FloatField(default=100.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(max_length=80)),
                ('rule', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=160)),
                ('confidence', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=160)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=32)),
                ('results', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
