# Generated by Django 6.0.8 on 2026-08-26 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawdownHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('drawdown', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('drawdown_percent', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdown_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('assessment_time', models.DateTimeField(auto_now_add=True)),
                ('adjusted_parameters', models.JSONField(blank=True, default=dict)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='execution.order')),
            ],
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='Default Risk Profile', max_length=120)),
                ('risk_level', models.CharField(choices=[('very_conservative', 'Very Conservative'), ('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive'), ('very_aggressive', 'Very Aggressive'), ('custom', 'Custom')], default='moderate', max_length=32)),
                ('max_risk_per_trade', models.DecimalField(decimal_places=6, default=0.02, max_digits=10)),
                ('max_daily_loss', models.DecimalField(decimal_places=6, default=0.04, max_digits=10)),
                ('max_daily_profit', models.DecimalField(decimal_places=6, default=0.06, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=6, default=0.1, max_digits=10)),
                ('max_open_positions', models.PositiveIntegerField(default=10)),
                ('max_exposure', models.DecimalField(decimal_places=6, default=0.35, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=160)),
                ('rule_type', models.CharField(choices=[('max_risk_per_trade', 'Max Risk Per Trade'), ('max_daily_loss', 'Max Daily Loss'), ('max_daily_profit', 'Max Daily Profit'), ('max_weekly_loss', 'Max Weekly Loss'), ('max_monthly_loss', 'Max Monthly Loss'), ('max_drawdown', 'Max Drawdown'), ('max_consecutive_losses', 'Max Consecutive Losses'), ('max_consecutive_wins', 'Max Consecutive Wins'), ('max_open_positions', 'Max Open Positions'), ('max_simultaneous_strategies', 'Max Simultaneous Strategies'), ('max_symbol_exposure', 'Max Symbol Exposure'), ('max_market_exposure', 'Max Market Exposure'), ('max_broker_exposure', 'Max Broker Exposure'), ('minimum_balance', 'Minimum Balance'), ('max_stake_limit', 'Max Stake Limit')], max_length=64)),
                ('value', models.DecimalField(decimal_places=8, max_digits=18)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='risk.riskprofile')),
            ],
            options={
                'ordering': ['priority', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40)),
                ('market', models.CharField(blank=True, max_length=80)),
                ('exposure_value', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symbol', 'market')},
            },
        ),
        migrations.CreateModel(
            name='KillSwitchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_kill_switches', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_switch_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'resolved_at'], name='risk_killsw_user_id_2b075d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='riskprofile',
            index=models.Index(fields=['user', 'risk_level'], name='risk_riskpr_user_id_328d60_idx'),
        ),
    ]
