# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='killswitchevent',
            new_name='risk_killsw_user_id_2b075d_idx',
            old_name='risk_killsw_user_id_41f59b_idx',
        ),
        migrations.RenameIndex(
            model_name='riskprofile',
            new_name='risk_riskpr_user_id_328d60_idx',
            old_name='risk_riskpr_user_id_74d0f3_idx',
        ),
    ]
