# Generated manually for Phase 2 broker layer.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Broker', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=120, unique=True)), ('slug', models.SlugField(max_length=80, unique=True)), ('logo', models.ImageField(blank=True, null=True, upload_to='brokers/')), ('website', models.URLField(blank=True)), ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('maintenance', 'Maintenance')], default='active', max_length=24)), ('created_at', models.DateTimeField(auto_now_add=True))], options={'ordering': ['name']}),
        migrations.CreateModel(name='BrokerAccount', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('broker_account_id', models.CharField(max_length=120)), ('account_type', models.CharField(choices=[('demo', 'Demo'), ('real', 'Real')], default='demo', max_length=20)), ('currency', models.CharField(blank=True, max_length=12)), ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)), ('equity', models.DecimalField(decimal_places=8, default=0, max_digits=18)), ('margin', models.DecimalField(decimal_places=8, default=0, max_digits=18)), ('is_default', models.BooleanField(default=False)), ('is_connected', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='broker.broker')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to=settings.AUTH_USER_MODEL))], options={'unique_together': {('broker', 'broker_account_id')}}),
        migrations.CreateModel(name='BrokerToken', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('access_token', models.TextField()), ('refresh_token', models.TextField(blank=True)), ('expires_at', models.DateTimeField(blank=True, null=True)), ('last_refresh', models.DateTimeField(blank=True, null=True)), ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)), ('broker_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='broker.brokeraccount'))]),
        migrations.CreateModel(name='BrokerConnectionLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('status', models.CharField(max_length=50)), ('latency', models.FloatField(blank=True, null=True)), ('event', models.CharField(max_length=120)), ('created_at', models.DateTimeField(auto_now_add=True)), ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='broker.brokeraccount'))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='BrokerPermission', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('permission', models.CharField(max_length=80)), ('enabled', models.BooleanField(default=True)), ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='broker.broker'))], options={'unique_together': {('broker', 'permission')}}),
        migrations.AddIndex(model_name='brokeraccount', index=models.Index(fields=['user', 'is_default'], name='broker_brok_user_id_3f87ad_idx')),
        migrations.AddIndex(model_name='brokeraccount', index=models.Index(fields=['broker', 'is_connected'], name='broker_brok_broker__3417be_idx')),
        migrations.AddIndex(model_name='brokerconnectionlog', index=models.Index(fields=['broker_account', '-created_at'], name='broker_brok_broker__eb7036_idx')),
        migrations.AddIndex(model_name='brokerconnectionlog', index=models.Index(fields=['event'], name='broker_brok_event_1ef8c2_idx')),
    ]
