# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brokeraccount',
            new_name='broker_brok_user_id_23914c_idx',
            old_name='broker_brok_user_id_3f87ad_idx',
        ),
        migrations.RenameIndex(
            model_name='brokeraccount',
            new_name='broker_brok_broker__916baf_idx',
            old_name='broker_brok_broker__3417be_idx',
        ),
        migrations.RenameIndex(
            model_name='brokerconnectionlog',
            new_name='broker_brok_broker__b40b0c_idx',
            old_name='broker_brok_broker__eb7036_idx',
        ),
        migrations.RenameIndex(
            model_name='brokerconnectionlog',
            new_name='broker_brok_event_e035be_idx',
            old_name='broker_brok_event_1ef8c2_idx',
        ),
    ]
