# Generated by Django 6.0.8 on 2026-08-26 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('recommendation', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('WAIT', 'WAIT'), ('EXIT', 'EXIT'), ('REDUCE RISK', 'REDUCE RISK'), ('INCREASE POSITION', 'INCREASE POSITION'), ('DO NOT TRADE', 'DO NOT TRADE')], max_length=32)),
                ('confidence', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('risk_level', models.CharField(default='medium', max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('anomaly_type', models.CharField(max_length=64)),
                ('score', models.FloatField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('features', models.JSONField(default=dict)),
                ('feature_hash', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarketRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('regime', models.CharField(choices=[('trending', 'Trending'), ('strong_trend', 'Strong Trend'), ('sideways', 'Sideways'), ('volatile', 'Volatile'), ('low_volatility', 'Low Volatility'), ('accumulation', 'Accumulation'), ('distribution', 'Distribution'), ('breakout', 'Breakout'), ('reversal', 'Reversal')], max_length=32)),
                ('confidence', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('version', models.CharField(default='1.0.0', max_length=40)),
                ('algorithm', models.CharField(choices=[('random_forest', 'Random Forest'), ('xgboost', 'Xgboost'), ('lightgbm', 'Lightgbm'), ('catboost', 'Catboost'), ('extra_trees', 'Extra Trees'), ('svm', 'Svm'), ('logistic_regression', 'Logistic Regression'), ('lstm', 'Lstm'), ('gru', 'Gru'), ('cnn', 'Cnn'), ('transformer', 'Transformer'), ('ensemble', 'Ensemble')], max_length=64)),
                ('framework', models.CharField(default='sklearn', max_length=80)),
                ('status', models.CharField(choices=[('experimental', 'Experimental'), ('active', 'Active'), ('champion', 'Champion'), ('challenger', 'Challenger'), ('archived', 'Archived'), ('failed', 'Failed')], db_index=True, default='experimental', max_length=32)),
                ('accuracy', models.FloatField(default=0)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('f1_score', models.FloatField(default=0)),
                ('auc', models.FloatField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'algorithm'], name='ai_engine_a_status_e91dd9_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('prediction', models.CharField(max_length=64)),
                ('probability', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('expected_return', models.FloatField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-created_at'], name='ai_engine_p_symbol_993350_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='ai_engine.aimodel')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('training_dataset', models.CharField(blank=True, max_length=255)),
                ('feature_set', models.JSONField(blank=True, default=dict)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai_engine.aimodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('model', 'version')},
            },
        ),
    ]
