# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aimodel',
            new_name='ai_engine_a_status_e91dd9_idx',
            old_name='ai_engine_a_status_949410_idx',
        ),
        migrations.RenameIndex(
            model_name='prediction',
            new_name='ai_engine_p_symbol_993350_idx',
            old_name='ai_engine_p_symbol_3b9f94_idx',
        ),
        migrations.AlterField(
            model_name='marketregime',
            name='regime',
            field=models.CharField(choices=[('trending', 'Trending'), ('strong_trend', 'Strong Trend'), ('sideways', 'Sideways'), ('volatile', 'Volatile'), ('low_volatility', 'Low Volatility'), ('accumulation', 'Accumulation'), ('distribution', 'Distribution'), ('breakout', 'Breakout'), ('reversal', 'Reversal')], max_length=32),
        ),
    ]
