# Generated by Django 6.0.8 on 2026-08-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_prediction_outcome'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='predictionoutcome',
            new_name='ai_engine_p_correct_6bba0a_idx',
            old_name='ai_engine_po_correct_resolved_idx',
        ),
    ]
