# Generated by Django 6.0.8 on 2026-08-25 19:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(db_index=True, max_length=160)),
                ('optimizer', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(db_index=True, default='pending', max_length=24)),
                ('parameter_space', models.JSONField(blank=True, default=dict)),
                ('resource_limits', models.JSONField(blank=True, default=dict)),
                ('best_parameters', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict)),
                ('fitness', models.FloatField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('profit_factor', models.FloatField(default=0)),
                ('drawdown', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optimization_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='optimization.optimizationjob')),
            ],
        ),
    ]
