# Generated by Django 6.0.8 on 2026-08-26 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('message', models.TextField()),
                ('target_group', models.CharField(db_index=True, default='all_users', max_length=80)),
                ('status', models.CharField(db_index=True, default='queued', max_length=24)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('event', models.CharField(db_index=True, max_length=120)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('category', models.CharField(db_index=True, default='general', max_length=40)),
                ('subject', models.CharField(blank=True, max_length=220)),
                ('body', models.TextField()),
                ('language', models.CharField(default='en', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('message', models.TextField()),
                ('category', models.CharField(db_index=True, default='general', max_length=40)),
                ('priority', models.CharField(db_index=True, default='info', max_length=24)),
                ('status', models.CharField(db_index=True, default='queued', max_length=24)),
                ('channel', models.CharField(db_index=True, default='in_app', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(db_index=True, default='queued', max_length=24)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='enterprise_notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('quiet_hours', models.JSONField(blank=True, default=dict)),
                ('digest_frequency', models.CharField(default='immediate', max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status', 'priority'], name='enterprise__user_id_5f980d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'channel')},
        ),
    ]
