# Generated by Django 6.0.6 on 2026-08-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='enterprise__user_id_5f980d_idx',
            old_name='enterprise__user_id_1ec798_idx',
        ),
    ]
