# Generated by Django 6.0.8 on 2026-08-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_notifications', '0002_notificationchannelconnection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationchannelconnection',
            new_name='enterprise__user_id_72de89_idx',
            old_name='notifications_user_prov_status_idx',
        ),
    ]
